---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10
    
    steps:
      - name: Checkout out the codebase.
        uses: actions/checkout@v2 # predefined github actions from github

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule docker-compose yamllint ansible-lint molecule-docker
      
      - name: Run Molecule tests.
        run: molecule test
        eng:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}


