---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10
    
    steps:
      - name: Checkout out the codebase.
        uses: actions/checkup@v2 # predefined github actions from github

      - name: Set up Python 3.
        uses: action/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule docker yamllint ansible-lint
      
      - name: Run Molecule tests.
        run: molecule test



